modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="$mod_github/issues"

[[mods]]
modId="$mod_id"
version="$mod_version"
displayName="$mod_name"
#updateJSONURL="$mod_github/raw/$minecraft_version/update.json"
displayURL="$mod_github"
logoFile="${mod_id}.png"
credits="$mod_credits"
authors="$mod_authors"
description='''
$mod_description
'''

[[dependencies.$mod_id]]
    modId="neoforge"
    type="required"
    versionRange="[$neo_version,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.$mod_id]]
    modId="minecraft"
    type="required"
    versionRange="$minecraft_version_range"
    ordering="NONE"
    side="BOTH"

[[dependencies.$mod_id]]
    modId="farmersdelight"
    type="required"
    versionRange="1"
    ordering="NONE"
    side="BOTH"
